# Generated by Django 5.1.3 on 2024-12-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrument_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='mantenimiento',
            field=models.CharField(max_length=50),
        ),
    ]
