# Generated by Django 5.1.3 on 2024-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('instrument', models.CharField(max_length=50)),
                ('precio_tot', models.FloatField()),
                ('id_cliente', models.IntegerField()),
                ('id_sucursal', models.IntegerField()),
                ('id_empleado', models.IntegerField()),
            ],
        ),
    ]
