# Generated by Django 5.1.3 on 2024-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emple', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('puesto', models.CharField(max_length=50)),
                ('sueldo', models.FloatField()),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=250)),
                ('celular', models.IntegerField()),
            ],
        ),
    ]
