# Generated by Django 5.1.3 on 2024-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('espacio', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('encargado', models.CharField(max_length=50)),
            ],
        ),
    ]
