# Generated by Django 5.1.3 on 2024-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor',
            name='fecha_entre',
            field=models.CharField(max_length=50),
        ),
    ]
